baseURL = 'https://www.narnacle.com/'
languageCode = 'en-US'
title = "LunaR"

theme = 'moonwalk'

[menus]
	[[menus.main]]
		name = 'about'
		pageRef = '/about'

	[[menus.main]]
		name = 'blog'
		pageRef = '/blog'

	[[menus.main]]
		name = 'website'
		url = 'https://www.narnacle.com/'

[params]
	[params.author]
		email = 'narnacle@proton.me'
