ignorefiles = [ "content/templates" ]
baseURL = "https://www.narnacle.com/"
languageCode = "en-us"
title = "Narnacle's Dev Blog"
theme = "PaperModX"
languageName = "English"
pagination.pagerSize = 100
enableRobotsTXT = true
defaultTheme = "dark"

# SEO-related settings
[params]
description = "Narnacle's blog on Linux, and Selfhosting."
keywords = ["Linux", "Selfhosting", "Programming", "Golang"]
images = ["narnacle.png"]
favicon = "narnacle.png"
showtoc= true
tocopen = false
TocSide = 'right'
ShowReadingTime = true
ShowWordCount = true
ShowShareButtons = true
ShowCodeCopyButtons = true
defaultTheme = "dark"
canonicalURL = "{{ .Permalink }}"
author="Narnacle"

# Header settings
[params.header]
desktopMode = "fixed"
mobileMode = "auto"

# Menu configuration
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    title = "Posts"

  [[menu.main]]
    weight = 2
    identifier = "About"
    name = "About"
    url = "/about/"
    title = "About"

    [[menu.main]]
    weight = 3
    identifier = "Newsletter"
    name = "NEWSLETTER"
    url = "https://rb.gy/8xsd0h"
    title = "NEWSLETTER"
    params.external = true

    [[menu.main]]
    weight = 4
    identifier = "Search"
    name = "Search"
    url = "/search/"
    title = "Search the site"

# Home Info Params
[params.homeInfoParams]
Title = "Hi, I'm N4rn4cl3"
Content = "I post interesting things I stumble upon. Mostly about [<u>**linux**</u>](../../tags/linux), and [<u>**programming**</u>](../../tags/programming). I also love [<u>**selfhosting**</u>](../../tags/selfhosting) stuff."

# Social Icons
[[params.socialIcons]]
name = "github"
url = "https://github.com/narnacle"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/narnacle"

[[params.socialIcons]]
name = "email"
url = "/about/#get-in-touch"

[[params.socialIcons]]
name = "monero"
url = "/donate/"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@narnacle"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

# Sitemap settings
[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

# Markup settings
[markup.goldmark.renderer]
unsafe = true

# Logo settings
[params.logo]
icon = "narnacle.png"

[params.opengraph]
enable = true
title = "{{ .Title }}"
description = "{{ .Params.description }}"
image = "{{ .Params.images }}"

[params.twitter]
enable = true
card = "summary_large_image"
title = "{{ .Title }} - Narnacle's blog"
description = "{{ .Params.description }}"
image = "{{ .Params.images }}"

[params.search]
 enabled = true

[outputs]
home = [ "HTML", "RSS", "JSON"]